#!/bin/bash
#
# Tests for the settings utility that draws on the framebuffer:
# tools/settings-ui/config.c (tty2oledplus_config), the table and the changes
# tty2oledplus_settings.sh passes it and takes back, and
# tty2oledplus_preview.sh, which shows a setting on the display while it is
# changed.
#
# The utility is built for this machine and run against a file standing in
# for /dev/fb0, with its keys on a pipe - the bytes a terminal sends for the
# arrows, Enter and Escape, which is how a pad arrives on a MiSTer too. What
# is checked is what it hands back and what it told the preview; the pixels
# only for what a picture cannot be argued with about: that something is
# drawn, in cyan and nothing else, inside what a 15kHz CRT shows.
#
# The preview is run against a pipe standing in for the display's port, and
# what reaches it compared with what the daemon would send.
#
#   ./tests/test-config.sh

set -u

HERE="$(cd "$(dirname "${0}")" && pwd)"
ROOT="$(dirname "${HERE}")"
TMP="${HERE}/fixtures/tmp/config"
rm -rf "${TMP}"; mkdir -p "${TMP}/install"

INSTALL="${TMP}/install"

PASS=0; FAIL=0
ok() {
  local label="${1}" got="${2}" want="${3}"
  if [ "${got}" = "${want}" ]; then
    PASS=$((PASS+1)); printf '  \033[32mok\033[0m   %s\n' "${label}"
  else
    FAIL=$((FAIL+1))
    printf '  \033[31mFAIL\033[0m %s\n       want: [%s]\n       got:  [%s]\n' "${label}" "${want}" "${got}"
  fi
}
section() { printf '\n\033[1m%s\033[0m\n' "${1}"; }

if ! command -v gcc >/dev/null 2>&1; then
  printf '\033[33mgcc not found - skipping the settings utility tests\033[0m\n'
  exit 0
fi

# ---------------------------------------------------------------------------
section "building it"
# ---------------------------------------------------------------------------
"${ROOT}/tools/build-config.sh" --host > "${TMP}/build.out" 2>&1; RC="${?}"
ok "builds clean under -Wall -Wextra -Werror, with ASan and UBSan" "${RC}" "0"
[ "${RC}" -eq 0 ] || { cat "${TMP}/build.out"; printf '\n\033[1mResults:\033[0m %d passed, %d failed\n' "${PASS}" "$((FAIL))"; exit 1; }
BIN="${ROOT}/tools/settings-ui/build/host/tty2oledplus_config"

ok "the fonts are the ones genfont.sh makes: four, generated" \
   "$(grep -c '^static const Font font_' "${ROOT}/tools/settings-ui/fonts.h"):$(grep -c 'Generated by tools/settings-ui/genfont.sh' "${ROOT}/tools/settings-ui/fonts.h")" "4:1"

# The real install's inis, so the table is the real one.
cp "${ROOT}/tty2oled-system.ini" "${INSTALL}/"
printf '# mine\nCONTRAST="180"\nTRANSITION="31"\n' > "${INSTALL}/tty2oled-user.ini"

# The editor as a library, for its table.
# shellcheck source=../tools/tty2oledplus_settings.sh
T2OP_SETTINGS_LIB=yes T2OP_INSTALL="${INSTALL}" T2OP_UI_LIB="${ROOT}/tools/tty2oledplus_ui.sh" \
  . "${ROOT}/tools/tty2oledplus_settings.sh"

TABLE="${TMP}/table.tsv"
dump_table > "${TABLE}"

# ---------------------------------------------------------------------------
section "the table the script hands over"
# ---------------------------------------------------------------------------
NSET=0; BAD=""
for c in ${CATEGORIES}; do
  while IFS='|' read -r k _; do
    NSET=$((NSET + 1))
    want="$(current_value "${k}")"
    got="$(awk -F'\t' -v k="${k}" '$1 == "V" && $2 == k { print $3 }' "${TABLE}")"
    [ "${want}" = "${got}" ] || BAD="${BAD} ${k}"
    want="$(default_value "${k}")"
    got="$(awk -F'\t' -v k="${k}" '$1 == "D" && $2 == k { print $3 }' "${TABLE}")"
    [ "${want}" = "${got}" ] || BAD="${BAD} ${k}:default"
  done < <(settings_in "${c}")
done
ok "every setting the menus offer is in it" "$(grep -c '^S' "${TABLE}")" "${NSET}"
ok "with the value and the default ini_get finds, though read in one pass" "${BAD}" ""
ok "a section a line, each with its line of help" \
   "$(awk -F'\t' '$1 == "C" && $3 != "" && $4 != ""' "${TABLE}" | wc -l | tr -d ' ')" "$(printf '%s\n' ${CATEGORIES} | wc -l | tr -d ' ')"
ok "an enum's spec is its pairs, not the variable's name" \
   "$(awk -F'\t' '$1 == "S" && $2 == "TRANSITION" { print ($4 ~ /^-2=Fade/) }' "${TABLE}")" "1"
ok "the pinned fields are chosen from the shown ones" \
   "$(awk -F'\t' '$1 == "S" && $2 == "METADATA_PINNED" { print $4 }' "${TABLE}")" "@METADATA_FIELDS"
# A caption for a key that is not a setting would be a divider that never
# appears, and nobody would be told.
LOST=""
while IFS='=' read -r k _; do
  grep -q "^S	${k}	" "${TABLE}" || LOST="${LOST} ${k}"
done <<< "${SUBSECTIONS}"
ok "every sub-section starts at a setting that is offered" "${LOST}" ""
ok "and each is a divider in the table, right above that setting" \
   "$(grep -c '^G' "${TABLE}"):$(grep -A1 '^G	Super Attract Mode$' "${TABLE}" | tail -n1 | cut -f1,2)" \
   "$(printf '%s\n' "${SUBSECTIONS}" | grep -c .):S	SAM_HEADER"
ok "nothing is pending in a fresh one" "$(grep -c '^P' "${TABLE}")" "0"
PENDING[CONTRAST]="77"
ok "what is changed and not saved goes along" "$(dump_table | grep -c "^P	CONTRAST	77$")" "1"
PENDING=()

printf 'A="1"\nB=two # note\nC='"'"'three'"'"'\n  D="four" # x\n#E="5"\nA="6"\n' > "${TMP}/odd.ini"
ok "ini_dump reads what ini_get reads: quotes, comments, the last one wins" \
   "$(ini_dump "${TMP}/odd.ini" | LC_ALL=C sort | tr '\t\n' '= ')" "A=6 B=two C=three D=four "

# ---------------------------------------------------------------------------
# Driving it. Keys are what a terminal sends.
# ---------------------------------------------------------------------------
U=$'\033[A'; D=$'\033[B'; L=$'\033[D'; R=$'\033[C'; OK=$'\r'; ESC=$'\033'; END=$'\033[F'
OUT="${TMP}/out.txt"; FB="${TMP}/fb.raw"; PV="${TMP}/preview.txt"

run() {  # run <keys> [more options] - the exit code in RC
  local keys="${1}"; shift
  rm -f "${OUT}" "${PV}"
  printf '%s' "${keys}" | "${BIN}" --table "${TABLE}" --out "${OUT}" --fb "${FB}" \
    --geometry 320x240x32 --preview "cat > '${PV}'" "$@" 2> "${TMP}/stderr"
  RC="${?}"
}
out() { tr '\n' '|' < "${OUT}"; }
# The sections, in order: display console arcade dvd panel transition updates advanced.
PANEL="${D}${D}${D}${D}${OK}"            # Brightness and burn-in; CONTRAST is first
TRANS="${D}${D}${D}${D}${D}${OK}"        # Changing picture; TRANSITION is first
DISPLAY_SEC="${OK}"                      # What the display shows; SHOW_METADATA is first
CONSOLE="${D}${OK}"                      # METADATA_FIELDS, METADATA_PINNED, SHOW_DESCRIPTION
ARCADE="${D}${D}${OK}"                   # ARCADE_FIELDS, ARCADE_FIELDS_WIDE, ARCADE_PINNED

# ---------------------------------------------------------------------------
section "leaving"
# ---------------------------------------------------------------------------
run ""
ok "the keys running out is its own exit code" "${RC}" "13"
ok "and sanitizers found nothing" "$(grep -c 'ERROR\|runtime error' "${TMP}/stderr")" "0"
run "${ESC}"
ok "Cancel with nothing changed leaves" "${RC}:$(out)" "10:"
run "${PANEL}${R}${ESC}${ESC}${OK}"
ok "Cancel with a change asks, and Save is the default" "${RC}:$(out)" "0:CONTRAST=181|"
run "${PANEL}${R}${ESC}${ESC}${R}${OK}"
ok "Discard leaves with nothing to save" "${RC}:$(out)" "10:"
run "${PANEL}${R}${ESC}${ESC}${R}${R}${OK}"
ok "Stay goes back to the settings" "${RC}:$(out)" "13:CONTRAST=181|"
run "${PANEL}${R}${ESC}${ESC}${ESC}"
ok "and so does Cancel on the question" "${RC}" "13"
run "${PANEL}${R}${ESC}${END}${OK}"
ok "Save and exit is the last row of the main screen" "${RC}:$(out)" "0:CONTRAST=181|"
run "${U}${OK}"
ok "which is Exit when nothing changed" "${RC}:$(out)" "10:"

# ---------------------------------------------------------------------------
section "a switch, a slider, a selector"
# ---------------------------------------------------------------------------
run "${DISPLAY_SEC}${L}"
ok "Left switches off" "$(out)" "SHOW_METADATA=no|"
run "${DISPLAY_SEC}${L}${R}"
ok "Right switches on again, and nothing is changed after all" "$(out)" ""
run "${DISPLAY_SEC}${OK}"
ok "OK flips a switch" "$(out)" "SHOW_METADATA=no|"

run "${PANEL}${L}${L}${L}"
ok "Left moves a slider down a step at a time" "$(out)" "CONTRAST=177|"
run "${PANEL}${R}${R}${R}${R}${R}${R}${R}${R}${R}${R}${R}${R}"
# Eight single steps, then fives - on the fives' grid: 188, 190, 195, 200, 205.
ok "a held direction speeds up" "$(out)" "CONTRAST=205|"
HOLD=""; for _ in $(seq 60); do HOLD="${HOLD}${R}"; done
run "${PANEL}${HOLD}"
ok "and stops at the top" "$(out)" "CONTRAST=255|"
run "${PANEL}${D}${R}"
ok "a slider with a step moves by it" "$(out)" "CONTRAST_FADE_MS=850|"
printf 'CONTRAST_FADE_MS="820"\n' >> "${INSTALL}/tty2oled-user.ini"; dump_table > "${TABLE}"
run "${PANEL}${D}${R}"
ok "and onto its grid from a value that is off it" "$(out)" "CONTRAST_FADE_MS=850|"
run "${PANEL}${D}${L}"
ok "either way" "$(out)" "CONTRAST_FADE_MS=800|"
sed -i '/CONTRAST_FADE_MS/d' "${INSTALL}/tty2oled-user.ini"; dump_table > "${TABLE}"

run "${TRANS}${R}"
ok "Right moves a selector to the next choice" "$(out)" "TRANSITION=32|"
run "${TRANS}${L}${L}"
ok "Left to the one before" "$(out)" "TRANSITION=23|"

# Dividers take rows on screen and none of the highlight's stops: the fifth
# Down in the first section is the sixth setting, whatever is drawn between.
run "${DISPLAY_SEC}${D}${D}${D}${D}${D}"
ok "the highlight steps over a sub-section's divider" "$(tail -n1 "${PV}")" "focus SAM_TIMER"
run "${DISPLAY_SEC}${U}${OK}"
ok "and Up from the first setting wraps to the last" "$(tail -n1 "${PV}"):$(out)" "focus VSCROLL_SPEED:"

# ---------------------------------------------------------------------------
section "the popups: a list, a number, a keyboard"
# ---------------------------------------------------------------------------
run "${TRANS}${OK}${D}${D}${OK}"
ok "OK on a selector opens the list, on the choice in force" "$(out)" "TRANSITION=33|"
run "${TRANS}${OK}${D}${D}${ESC}"
ok "Cancel in the list puts the old one back" "$(out)" ""
ok "and the display is told it is back" "$(grep '^set TRANSITION' "${PV}" | tail -n1)" "set TRANSITION 31"

run "${PANEL}${OK}${U}${U}${OK}"
ok "the number editor: Up adds one to the digit" "$(out)" "CONTRAST=182|"
run "${PANEL}${OK}${L}${D}${D}${D}${OK}"
ok "Left moves to the tens" "$(out)" "CONTRAST=150|"
run "${PANEL}${OK}${L}${L}${U}${OK}"
ok "past the top stops at the top" "$(out)" "CONTRAST=255|"
run "${PANEL}${OK}${D}${D}${ESC}"
ok "Cancel undoes it" "$(out)" ""
run "${PANEL}${OK}${L}${L}${D}${D}42${OK}"
ok "a keyboard's digits go in at the right" "$(out)" "CONTRAST=42|"
run "${PANEL}${D}${D}${D}${D}${D}${OK}${U}${U}${U}${U}${U}-${OK}"
ok "a minus that would go below the least stops at it" "$(out)" ""
run "${PANEL}${D}${D}${D}${D}${D}${OK}${U}${U}${U}${OK}"
ok "(and Up from -1 counts up)" "$(out)" "DIM_WAKE=2|"

SAM="${DISPLAY_SEC}${D}${D}${D}${D}"     # SAM_HEADER_TEXT
# The fifth row is the actions: Aa, Space, Delete, Clear, Done.
run "${SAM}${OK}${D}${D}${D}${D}${R}${R}${R}${OK}"
ok "the keyboard: Clear empties the field" "$(out)" "SAM_HEADER_TEXT=|"
run "${SAM}${OK}${D}${D}${D}${D}${R}${R}${R}${OK}${U}${U}${U}${U}${OK}${R}${OK}${ESC}"
ok "Cancel undoes all of it" "$(out)" ""
run "${SAM}${OK}"$'\t'"${L}${L}${OK}${U}${U}${U}${R}${OK}${D}${D}${D}"$'\t'"${OK}${ESC}${ESC}${OK}"
ok "Delete takes the last character, a key adds one, Done keeps it" "$(out)" "SAM_HEADER_TEXT=Super Attract Modu|"
run "${SAM}${OK}"$'\177\177\177\177'"Demo!${OK}${ESC}${ESC}${OK}"
ok "a real keyboard types straight in, and its Enter is Done" "$(out)" "SAM_HEADER_TEXT=Super Attract Demo!|"
run "${SAM}${OK}"$'\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177'"a\"b\$c\`d'e\\f${OK}${ESC}${ESC}${OK}"
ok "what an ini value cannot hold is not typed" "$(out)" "SAM_HEADER_TEXT=abcdef|"
LONG=""; for _ in $(seq 40); do LONG="${LONG}x"; done
run "${SAM}${OK}${LONG}${OK}${ESC}${ESC}${OK}"
ok "nor more than the setting's length" "$(awk -F= '{ print length($2) }' "${OUT}")" "24"

# ---------------------------------------------------------------------------
section "lists: ticking, order, and what depends on them"
# ---------------------------------------------------------------------------
FIELDS="$(current_value METADATA_FIELDS)"; PINNED="$(current_value METADATA_PINNED)"
FIRST="${FIELDS%% *}"; REST="${FIELDS#* }"; SECOND="${REST%% *}"
run "${CONSOLE}${OK}${R}${ESC}${ESC}${ESC}${OK}"
ok "Right moves a ticked field later" "$(grep -c "^METADATA_FIELDS=${SECOND} ${FIRST} " "${OUT}")" "1"
run "${CONSOLE}${OK}${R}${L}${ESC}${ESC}${ESC}"
ok "and Left back again" "$(out)" ""
run "${CONSOLE}${OK}${OK}${ESC}${ESC}${ESC}${OK}"
ok "OK unticks: the field leaves the list" "$(grep -c "^METADATA_FIELDS=${REST}$" "${OUT}")" "1"
ok "and the pinned list with it, when it was pinned there" \
   "$(grep '^METADATA_PINNED=' "${OUT}")" \
   "$(case " ${PINNED} " in *" ${FIRST} "*) printf 'METADATA_PINNED=%s' "$(list_intersect "${PINNED}" "${REST}")" ;; esac)"
run "${CONSOLE}${OK}${OK}${ESC}${D}${OK}"
ok "the pinned checklist offers only what is shown" "$(grep -c "focus METADATA_PINNED" "${PV}")" "1"
# Unticked goes to the end of the unticked; ticking it again appends it.
NF="$(printf '%s' "${FIELDS}" | wc -w)"
DOWN=""; for _ in $(seq $((NF - 1))); do DOWN="${DOWN}${D}"; done
run "${CONSOLE}${OK}${OK}${DOWN}${OK}${ESC}${ESC}${ESC}${OK}"
ok "ticked again it goes on the end, the rest in their order" \
   "$(grep -c "^METADATA_FIELDS=${REST} ${FIRST}$" "${OUT}")" "1"

AF="$(current_value ARCADE_FIELDS)"
run "${ARCADE}${D}${D}${L}${ESC}${ESC}${OK}"
ok "a leading run gets shorter from the end" \
   "$(grep '^ARCADE_PINNED=' "${OUT}")" "ARCADE_PINNED=$(list_prefix "${AF}" $(( $(printf '%s' "$(current_value ARCADE_PINNED)" | wc -w) - 1 )))"
run "${ARCADE}${D}${D}${R}${R}${R}${R}${R}${ESC}${ESC}${OK}"
ok "and is three fields at most" "$(grep '^ARCADE_PINNED=' "${OUT}")" "ARCADE_PINNED=$(list_prefix "${AF}" 3)"
run "${ARCADE}${OK}${R}${ESC}${ESC}${ESC}${OK}"
ok "reordering the list it runs along reorders it too" \
   "$(grep '^ARCADE_PINNED=' "${OUT}")" "ARCADE_PINNED=$(list_prefix "$(grep '^ARCADE_FIELDS=' "${OUT}" | cut -d= -f2)" "$(printf '%s' "$(current_value ARCADE_PINNED)" | wc -w)")"

# ---------------------------------------------------------------------------
section "back to the defaults"
# ---------------------------------------------------------------------------
run "${U}${U}${OK}${OK}"
ok "the answer already highlighted is No" "$(out)" ""
run "${U}${U}${OK}${R}${OK}${D}${OK}"
ok "Yes puts back what differs from the release, to be saved" "${RC}:$(LC_ALL=C sort "${OUT}" | tr '\n' '|')" "0:CONTRAST=$(default_value CONTRAST)|TRANSITION=$(default_value TRANSITION)|"

# ---------------------------------------------------------------------------
section "what the preview is told"
# ---------------------------------------------------------------------------
run "${PANEL}${R}${R}${R}${D}"
ok "the highlighted setting, and where a value ended up - not every step" \
   "$(tr '\n' '|' < "${PV}")" "focus -|set CONTRAST 183|focus CONTRAST_FADE_MS|"
run "${PANEL}${R}${ESC}${ESC}${R}${OK}"
ok "a change discarded is taken back on the display" "$(tail -n1 "${PV}")" "set CONTRAST 180"
PENDING[CONTRAST]="99"; dump_table > "${TABLE}"; PENDING=()
run ""
ok "changes from before this run, not saved, are told again" "$(grep -c '^set CONTRAST 99$' "${PV}")" "1"
ok "and still handed back" "$(out)" "CONTRAST=99|"
dump_table > "${TABLE}"
run "${PANEL}${R}" --preview "exit 3"
ok "a preview that dies takes nothing with it" "${RC}:$(out)" "13:CONTRAST=181|"

# ---------------------------------------------------------------------------
section "the picture"
# ---------------------------------------------------------------------------
# 320x240, 32 bits, blue-green-red-x: red must be nothing anywhere.
pixels() {  # pixels <file> <bytes a pixel> - "lit red" counts
  python3 - "$1" "$2" <<'EOF'
import sys
d = open(sys.argv[1], 'rb').read(); n = int(sys.argv[2])
lit = red = 0
for i in range(0, len(d), n):
    if n == 4:
        b, g, r = d[i], d[i + 1], d[i + 2]
    else:
        v = d[i] | d[i + 1] << 8
        r, g, b = v >> 11, (v >> 5) & 63, v & 31
    if g or b: lit += 1
    if r: red += 1
    if (g >> (0 if n == 4 else 1)) != b: red += 1      # green and blue together: cyan
print(lit > 1000, red)
EOF
}
run "" --dump "${TMP}/main.pgm"
ok "something is drawn, and all of it cyan" "$(pixels "${FB}" 4)" "True 0"
ok "sixteen levels and no more" \
   "$(python3 -c "
import sys
d = open(sys.argv[1], 'rb').read()
d = d[len(d) - 320 * 240:]
print(all(v % 17 == 0 for v in d), len(set(d)) > 4)" "${TMP}/main.pgm")" "True True"
# Every screen, and every popup over one: nothing lit in the margin a 15kHz
# CRT hides - 16 pixels at the sides, 12 above and below.
MARGIN=""
for keys in "" "${PANEL}" "${DISPLAY_SEC}${D}${D}${D}${D}${D}${D}${D}${D}${D}${D}${D}" "${TRANS}${OK}" "${PANEL}${OK}" "${SAM}${OK}" "${CONSOLE}${OK}" "${PANEL}${R}${ESC}${ESC}" "${DISPLAY_SEC}${U}"; do
  run "${keys}" --dump "${TMP}/shot.pgm"
  MARGIN="${MARGIN}$(python3 -c "
import sys
d = open(sys.argv[1], 'rb').read()
d = d[len(d) - 320 * 240:]
bad = sum(1 for y in range(240) for x in range(320)
          if d[y * 320 + x] and (x < 16 or x >= 304 or y < 12 or y >= 228))
print(bad)" "${TMP}/shot.pgm") "
done
ok "nothing is drawn where a CRT's overscan would hide it" "${MARGIN}" "0 0 0 0 0 0 0 0 0 "

rm -f "${FB}"
printf '' | "${BIN}" --table "${TABLE}" --out "${OUT}" --fb "${FB}" --geometry 320x240x16 2>/dev/null
ok "a 16-bit framebuffer gets the same, in its own format" "$(wc -c < "${FB}" | tr -d ' '):$(pixels "${FB}" 2)" "153600:True 0"
rm -f "${FB}"
printf '' | "${BIN}" --table "${TABLE}" --out "${OUT}" --fb "${FB}" --geometry 720x480x32 2>/dev/null
ok "a bigger one gets it doubled and centred" \
   "$(python3 -c "
import sys
d = open(sys.argv[1], 'rb').read()
def lit(x, y): return d[(y * 720 + x) * 4 + 1] != 0
cols = [x for x in range(720) if any(lit(x, y) for y in range(480))]
rows = [y for y in range(480) if any(lit(x, y) for x in range(720))]
print(min(cols) >= 40 + 32, max(cols) < 40 + 608, min(rows) >= 24, max(rows) < 456,
      all(lit(x, y) == lit(x + 1, y) == lit(x, y + 1) for y in rows[::2][:40] for x in range(40, 680, 2)))" "${FB}")" \
   "True True True True True"
printf '' | "${BIN}" --table "${TABLE}" --out "${OUT}" --fb "${FB}" --geometry 256x192x32 2>/dev/null; RC="${?}"
ok "one too small to hold it is refused, for the menus to take over" "${RC}" "12"
printf '' | "${BIN}" --table "${TMP}/no-such-table" --out "${OUT}" --fb "${FB}" --geometry 320x240x32 2>/dev/null; RC="${?}"
ok "and so is no table" "${RC}" "12"

# ---------------------------------------------------------------------------
section "the script around it"
# ---------------------------------------------------------------------------
# A stand-in for the init script that records what it is asked.
cat > "${INSTALL}/S60tty2oled" <<EOF
#!/bin/bash
echo "\$1" >> "${TMP}/init.log"
[ "\$1" = "status" ] && exit \${T2OP_TEST_STATUS:-0}
exit 0
EOF
chmod +x "${INSTALL}/S60tty2oled"
# ...and for the preview: there is a display, and what it is told is kept.
cat > "${INSTALL}/tty2oledplus_preview.sh" <<EOF
#!/bin/bash
[ "\$3" = "--check" ] && exit \${T2OP_TEST_DISPLAY:-0}
cat > "${TMP}/script-preview.txt"
EOF
INIT="${INSTALL}/S60tty2oled"; PREVIEW_TOOL="${INSTALL}/tty2oledplus_preview.sh"
UI_BIN_SRC="${BIN}"; UI_FBDEV="${FB}"; UI_BIN_COPY="${TMP}/config.copy"
SLEEPFILE="${TMP}/sleep"; DAEMONLOG="${TMP}/daemon.log"
export T2OP_CONFIG_ARGS="--geometry 320x240x32"
RESTART="yes"

# Taking the screen: where there is one, and a utility to draw on it.
ok "--dialog is the menus, whatever is there" "$(T2OP_UI=dialog ui_begin; echo $?)" "1"
ok "an install without the utility has none" "$(UI_BIN_SRC="${TMP}/nope" T2OP_UI=fb ui_begin; echo $?)" "1"
ok "no framebuffer, no screen" "$(UI_FBDEV="${TMP}/no-such-fb" ui_begin; echo $?)" "1"
ok "a framebuffer it cannot draw on is found out before the first screen" \
   "$(T2OP_CONFIG_ARGS="--geometry 200x100x32" T2OP_UI=fb ui_begin; echo $?)" "1"
T2OP_UI=fb ui_begin; RC="${?}"
ok "with both, the screen is taken" "${RC}:$(ui_fb && echo yes)" "0:yes"
ok "by a copy of the utility in /tmp, which Update may then write over" \
   "$(cmp -s "${BIN}" "${UI_BIN_COPY}" && echo same):${T2OP_FB_BIN}" "same:${UI_BIN_COPY}"

ui() {  # ui <keys> - fb_ui with these keys; its exit code in RC
  rm -f "${TMP}/init.log" "${TMP}/script-preview.txt"
  printf '%s' "${1}" > "${TMP}/keys"
  fb_ui < "${TMP}/keys" 2> "${TMP}/stderr"; RC="${?}"
}
user() { grep -v '^#' "${INSTALL}/tty2oled-user.ini" | grep . | LC_ALL=C sort | tr '\n' '|'; }

ui "${PANEL}${R}${ESC}${END}${OK}"
ok "Save writes the user ini" "${RC}:$(user)" '0:CONTRAST="181"|TRANSITION="31"|'
ok "the daemon is stopped for the preview and started after, with what was saved" \
   "$(tr '\n' ' ' < "${TMP}/init.log")" "status stop start "
ok "the preview ran, and heard the change" "$(grep -c '^set CONTRAST 181$' "${TMP}/script-preview.txt")" "1"
ok "the user's own lines are still there" "$(grep -c '^# mine$' "${INSTALL}/tty2oled-user.ini")" "1"

ui "${PANEL}${L}${ESC}${ESC}${R}${OK}"
ok "Discard writes nothing" "${RC}:$(user)" '0:CONTRAST="181"|TRANSITION="31"|'
ok "and the daemon goes back to how it was found" "$(tr '\n' ' ' < "${TMP}/init.log")" "status stop start "
T2OP_TEST_STATUS=1 ui "${ESC}"
ok "which is stopped, if it was stopped" "$(T2OP_TEST_STATUS=1; tr '\n' ' ' < "${TMP}/init.log")" "status stop "

HOLD=""; for _ in $(seq 80); do HOLD="${HOLD}${R}"; done
ui "${PANEL}${HOLD}${ESC}${END}${OK}"
ok "a setting put back to its default is removed, not written" "$(user)" 'TRANSITION="31"|'

touch "${SLEEPFILE}"
ui "${PANEL}${L}${ESC}${END}${OK}"
ok "while another program has the display: no preview, the daemon left alone until Save" \
   "$(tr '\n' ' ' < "${TMP}/init.log"):$(test -e "${TMP}/script-preview.txt" && echo preview)" "restart :"
rm -f "${SLEEPFILE}"
export T2OP_TEST_DISPLAY=1
ui "${ESC}"
ok "no display: no preview, and nothing stopped" "$(cat "${TMP}/init.log" 2>/dev/null):$(test -e "${TMP}/script-preview.txt" && echo preview)" ":"
unset T2OP_TEST_DISPLAY
RESTART="no"
ui "${PANEL}${L}${ESC}${END}${OK}"
ok "--no-restart: saved, the daemon and the display untouched" \
   "$(user):$(cat "${TMP}/init.log" 2>/dev/null)" 'CONTRAST="253"|TRANSITION="31"|:'
RESTART="yes"

# What comes back is checked like anything typed into a menu.
PENDING=(); dump_table > /dev/null
printf 'CONTRAST=999\nSHOW_METADATA=maybe\nTRANSITION=77\nSAM_HEADER_TEXT=a"b$(reboot)\nNOT_A_SETTING=1\nMETADATA_FIELDS=System $(x) Year\nDIM_AFTER=abc\n' > "${TMP}/back.txt"
take_changes "${TMP}/back.txt"
ok "a number is kept in its range" "${PENDING[CONTRAST]:-}" "255"
ok "a switch is yes or no" "${PENDING[SHOW_METADATA]-unset}" "unset"
ok "a choice is one of the choices" "${PENDING[TRANSITION]-unset}" "unset"
ok "text loses what would be shell" "${PENDING[SAM_HEADER_TEXT]:-}" "ab(reboot)"
ok "a list is words" "${PENDING[METADATA_FIELDS]:-}" "System Year"
ok "what is not a number is not taken" "${PENDING[DIM_AFTER]-unset}" "unset"
ok "nor a key the editor does not offer" "${PENDING[NOT_A_SETTING]-unset}" "unset"
PENDING=()

# The utility unable to draw: the menus take over, not an error.
CONFIG_BIN_REAL="${T2OP_FB_BIN}"
printf '#!/bin/bash\nexit 12\n' > "${TMP}/cannot"; chmod +x "${TMP}/cannot"
T2OP_FB_BIN="${TMP}/cannot"
ui ""
ok "a utility that cannot draw hands over to the menus" "${RC}" "1"
ok "with the daemon started again" "$(tail -n1 "${TMP}/init.log")" "start"
T2OP_FB_BIN="${CONFIG_BIN_REAL}"

# ---------------------------------------------------------------------------
section "the other screens: a menu, a question, a checklist, a command"
# ---------------------------------------------------------------------------
scr() {  # scr <keys> <screen> <args...> - the exit code in RC, what was chosen in OUT
  local keys="${1}"; shift
  rm -f "${OUT}"
  printf '%s' "${keys}" | "${BIN}" "$@" 2> "${TMP}/stderr"
  RC="${?}"
}
G=(--out "${OUT}" --fb "${FB}" --geometry 320x240x32)
MENU=(menu "${G[@]}" --subtitle "1.0" -- a "Alpha" "The first." b "Beta" "The second." c "Gamma" "")

scr "${D}${D}${OK}" "${MENU[@]}"
ok "a menu hands back the tag that was highlighted" "${RC}:$(cat "${OUT}")" "0:c"
scr "${ESC}" "${MENU[@]}"
ok "Cancel is its own exit code, with nothing chosen" "${RC}:$(cat "${OUT}" 2>/dev/null)" "10:"
scr "${OK}" menu "${G[@]}" --default b -- a "Alpha" "" b "Beta" "" c "Gamma" ""
ok "it opens on the one asked for" "$(cat "${OUT}")" "b"
# Two screens off one pipe, as the launcher's are: the first must leave the
# second its keys.
printf '%s' "${D}${OK}${D}${D}${OK}" > "${TMP}/keys"
{ "${BIN}" "${MENU[@]}"; FIRST="$(cat "${OUT}")"; "${BIN}" "${MENU[@]}"; } < "${TMP}/keys" 2>/dev/null
ok "a screen reads its own keys and no more: the next one's stay in the pipe" "${FIRST}:$(cat "${OUT}")" "b:c"

ASK=(ask "${G[@]}" --title "Sure?" --text $'One line.\n\nAnother, long enough that it has to be wrapped somewhere along the way.' --buttons "No|Yes")
scr "${OK}" "${ASK[@]}"
ok "a question opens on its first button" "${RC}:$(cat "${OUT}")" "0:0"
scr "${R}${OK}" "${ASK[@]}"
ok "Right moves to the next" "$(cat "${OUT}")" "1"
scr "${ESC}" "${ASK[@]}"
ok "Cancel answers nothing" "${RC}:$(cat "${OUT}" 2>/dev/null)" "10:"
scr "${OK}" "${ASK[@]}" --default 1
ok "--default picks which button it opens on" "$(cat "${OUT}")" "1"

CHECK=(check "${G[@]}" --title "Pick" --ok-label "Go" -- x "Ex" on y "Why" off z "Zed" on)
scr "${END}${OK}" "${CHECK[@]}"
ok "a checklist hands back what was ticked" "${RC}:$(cat "${OUT}")" "0:x z"
scr "${OK}${D}${OK}${END}${OK}" "${CHECK[@]}"
ok "OK ticks and unticks" "$(cat "${OUT}")" "y z"
scr "${L}${END}${OK}" "${CHECK[@]}"
ok "Left unticks them all" "$(cat "${OUT}")" ""
scr "${R}${END}${OK}" "${CHECK[@]}"
ok "Right ticks them all" "$(cat "${OUT}")" "x y z"
scr "${ESC}" "${CHECK[@]}"
ok "Cancel is Cancel" "${RC}" "10"

RUN=(run --fb "${FB}" --geometry 320x240x32 --title "Working")
scr "" "${RUN[@]}" -- bash -c 'printf "\n==> A step\n    a note\n*** gone wrong\n"; exit 3'
ok "a command's exit code is the screen's" "${RC}" "3"
scr "" "${RUN[@]}" -- bash -c 'echo fine'
ok "also when it is nothing" "${RC}" "0"
scr "" "${RUN[@]}" -- "${TMP}/no-such-command"
ok "a command that cannot be run is a failure, not a hang" "${RC}" "127"
# A daemon started by the command keeps its end of the pipe: the updater
# starts one, and the screen must not wait for it.
T0="${SECONDS}"
scr "" "${RUN[@]}" -- bash -c 'sleep 20 & echo started'
ok "it ends when the command does, whatever the command left running" "${RC}:$(( SECONDS - T0 < 10 ))" "0:1"
scr "x" "${RUN[@]}" -- bash -c 'cat; echo "read nothing"'
ok "the command reads nothing: the keys are the screen's" "${RC}" "0"

MARGIN=""
for shot in menu ask check run; do
  case "${shot}" in
    menu)  scr "${D}" "${MENU[@]:0:1}" --dump "${TMP}/shot.pgm" "${MENU[@]:1}" ;;
    ask)   scr "${R}" "${ASK[@]}" --dump "${TMP}/shot.pgm" ;;
    check) scr "${D}" "${CHECK[@]:0:1}" --dump "${TMP}/shot.pgm" "${CHECK[@]:1}" ;;
    run)   scr "" run --fb "${FB}" --geometry 320x240x32 --dump "${TMP}/shot.pgm" -- bash -c 'for i in $(seq 40); do echo "==> line $i, which is a long one so that it reaches the right edge and wraps"; done' ;;
  esac
  MARGIN="${MARGIN}$(python3 -c "
import sys
d = open(sys.argv[1], 'rb').read()
d = d[len(d) - 320 * 240:]
print(sum(1 for y in range(240) for x in range(320) if d[y * 320 + x] and (x < 16 or x >= 304 or y < 12 or y >= 228)),
      sum(1 for v in d if v) > 500)" "${TMP}/shot.pgm") "
done
ok "each draws something, and nothing in a CRT's overscan" "${MARGIN}" "0 True 0 True 0 True 0 True "

"${BIN}" release --fb "${FB}" --geometry 320x240x32 </dev/null; RC="${?}"
ok "release leaves nothing of ours on the screen" \
   "${RC}:$(python3 -c "import sys; print(any(open(sys.argv[1], 'rb').read()))" "${FB}")" "0:False"

# ---------------------------------------------------------------------------
section "the launcher and its tools, on those screens"
# ---------------------------------------------------------------------------
# A fake /media/fat with the real launcher, uninstaller, scraper menu and
# settings script, and stand-ins for what they would run.
FAT="${TMP}/fat"; LI="${FAT}/tty2oledplus"
mkdir -p "${LI}/pics" "${FAT}/Scripts"
cp "${ROOT}/tools/tty2oledplus.sh" "${FAT}/Scripts/"
cp "${ROOT}/tools/tty2oledplus_ui.sh" "${ROOT}/tools/tty2oledplus_settings.sh" \
   "${ROOT}/tools/tty2oledplus_uninstall.sh" "${ROOT}/tools/tty2oledplus_scrape.sh" \
   "${ROOT}/tty2oled-system.ini" "${LI}/"
: > "${LI}/tty2oled-user.ini"
cat > "${LI}/tty2oledplus_update.sh" <<STUB
#!/bin/bash
printf '\n==> Updating\n    done\n'
echo "ran \$*" > "${TMP}/update.ran"
exit \${T2OP_TEST_UPDATE_RC:-0}
STUB
cat > "${LI}/S60tty2oled" <<STUB
#!/bin/bash
echo "\$1" >> "${TMP}/init2.log"
STUB
cat > "${LI}/tty2oled-bootimg.sh" <<STUB
#!/bin/bash
echo "bootimg \$*" >> "${TMP}/bootimg.log"
[ "\$1" = "status" ] && echo "BOOTIMG,custom"
exit 0
STUB
cat > "${LI}/tty2oledplus_scrape.py" <<STUB
#!/usr/bin/env python3
import sys
if "--list-systems" in sys.argv:
    print("NES\tNintendo Entertainment System"); print("SNES\tSuper Nintendo"); print("Arcade\tArcade")
else:
    open("${TMP}/scrape.ran", "w").write(" ".join(sys.argv[1:]))
    open(sys.argv[sys.argv.index("--summary") + 1], "w").write("NES: 3 games\n")
    print("==> Importing")
STUB
chmod +x "${LI}"/*.sh "${LI}/S60tty2oled" "${LI}/tty2oledplus_scrape.py"

launch() {  # launch <keys> - the launcher with these keys; its exit code in RC
  rm -f "${TMP}/update.ran" "${TMP}/scrape.ran" "${TMP}/bootimg.log" "${TMP}/init2.log"
  printf '%s' "${1}" > "${TMP}/keys"
  ( unset T2OP_FB T2OP_FB_BIN
    T2OP_FAT="${FAT}" T2OP_UI=fb T2OP_CONFIG_BIN="${BIN}" T2OP_FBDEV="${FB}" \
    T2OP_CONFIG_COPY="${TMP}/launch.copy" T2OP_CONFIG_ARGS="--geometry 320x240x32" \
      bash "${FAT}/Scripts/tty2oledplus.sh" < "${TMP}/keys" > "${TMP}/launch.out" 2>&1 )
  RC="${?}"
}

launch "${ESC}"
ok "Cancel on the menu leaves, quietly" "${RC}:$(cat "${TMP}/launch.out")" "0:"
launch "${D}${OK}"
ok "Update runs the updater on a screen of its own" "${RC}:$(cat "${TMP}/update.ran" 2>/dev/null)" "0:ran "
T2OP_TEST_UPDATE_RC=4 launch "${D}${OK}"
ok "and the launcher ends as the updater ended" "${RC}" "4"
ok "from a copy of the utility, the installed one free to be replaced" \
   "$(cmp -s "${BIN}" "${TMP}/launch.copy" && echo same)" "same"

launch "${OK}${ESC}${ESC}"
ok "Settings opens the editor, and Cancel there is back at the menu" "${RC}:$(cat "${TMP}/launch.out")" "0:"
launch "${OK}${OK}${L}${ESC}${END}${OK}${ESC}"
ok "what is saved there is saved" "$(grep -c '^SHOW_METADATA="no"$' "${LI}/tty2oled-user.ini")" "1"
: > "${LI}/tty2oled-user.ini"

launch "${D}${D}${OK}${OK}${D}${OK}${END}${OK}"
ok "Scrape metadata: the ticked systems go to the importer" \
   "$(grep -o -- '--systems [A-Za-z,]*' "${TMP}/scrape.ran" 2>/dev/null)" "--systems Arcade"
ok "and are remembered for next time" "$(cat "${LI}/scraped/.systems" 2>/dev/null)" "Arcade"
launch "${D}${D}${OK}${ESC}"
ok "Cancel there imports nothing" "$(test -e "${TMP}/scrape.ran" && echo ran)" ""
launch "${D}${D}${OK}${L}${END}${OK}${OK}${ESC}"
ok "nothing ticked is said, not imported" "$(test -e "${TMP}/scrape.ran" && echo ran)" ""

launch "${D}${D}${D}${OK}${OK}${OK}${ESC}"
ok "Boot screen with no picture says where to put one, and stores nothing" \
   "$(grep -c 'bootimg set' "${TMP}/bootimg.log" 2>/dev/null)" "0"
launch "${D}${D}${D}${OK}${D}${OK}${OK}${ESC}"
ok "going back to the built-in logo asks, and No is the answer highlighted" \
   "$(grep -c 'bootimg clear' "${TMP}/bootimg.log" 2>/dev/null)" "0"
launch "${D}${D}${D}${OK}${D}${OK}${R}${OK}${OK}${ESC}"
ok "Yes clears it" "$(grep -c 'bootimg clear' "${TMP}/bootimg.log" 2>/dev/null)" "1"

echo 'CONTRAST="9"' > "${LI}/tty2oled-user.ini"
launch "${END}${OK}${OK}"
ok "Uninstall: the button highlighted is Cancel, and it is back at the menu" \
   "${RC}:$(test -d "${LI}" && echo there)" "0:there"
launch "${END}${OK}${R}${OK}${ESC}"
ok "Cancel at the second question changes nothing either" "$(test -d "${LI}" && echo there)" "there"
launch "${END}${OK}${R}${OK}${OK}"
ok "Remove, keeping what is yours: the install goes" "${RC}:$(test -d "${LI}" && echo there)" "0:"
ok "the launcher with it" "$(test -e "${FAT}/Scripts/tty2oledplus.sh" && echo there)" ""
ok "and the settings are saved beside it" "$(cat "${FAT}/tty2oledplus-saved/tty2oled-user.ini" 2>/dev/null)" 'CONTRAST="9"'

# ---------------------------------------------------------------------------
section "the preview on the display"
# ---------------------------------------------------------------------------
# An install of the real scripts, a pipe for the port.
PI="${TMP}/pinst"; mkdir -p "${PI}"
sed "s|/media/fat/tty2oledplus|${PI}|g" "${ROOT}/tty2oled-system.ini" > "${PI}/tty2oled-system.ini"
: > "${PI}/tty2oled-user.ini"
cp "${ROOT}/tty2oled.sh" "${ROOT}/tty2oled-meta.sh" "${ROOT}/tools/tty2oled-port.sh" \
   "${ROOT}/tools/tty2oledplus_preview.sh" "${PI}/"
mkdir -p "${PI}/pics/banner" "${PI}/pics/icon" "${PI}/pics/arcade"
for b in snes genesis menu dvd; do printf 'a\nb\nc\n00\n' > "${PI}/pics/banner/${b}.gsc"; done
for b in snes dvd; do printf 'a\nb\nc\n00\n' > "${PI}/pics/icon/${b}.gsc"; done
head -c 8192 /dev/zero > "${PI}/pics/arcade/wheels.bin"
printf '# frames 1\ngalaga|0\n' > "${PI}/pics/arcade/wheels.idx"

preview() {  # preview <lines...> - what reached the port, a command a line, in WIRE
  local line
  rm -f "${TMP}/tty.fifo"; mkfifo "${TMP}/tty.fifo"
  exec 9<>"${TMP}/tty.fifo"
  cat <&9 > "${TMP}/tty.log" & local reader=$!
  # "~" is a pause: lines that arrive together are taken together.
  for line in "$@"; do if [ "${line}" = "~" ]; then sleep 0.3; else printf '%s\n' "${line}"; fi; done \
    | T2OP_PREVIEW_TTY="${TMP}/tty.fifo" T2OP_PREVIEW_TICK=0.05 T2OP_PREVIEW_FW="${VERSION}" \
    LC_ALL=C bash "${PI}/tty2oledplus_preview.sh" --install "${PI}" > /dev/null 2>&1
  sleep 0.2; kill "${reader}" 2>/dev/null; wait "${reader}" 2>/dev/null
  exec 9>&-
  WIRE="$(LC_ALL=C grep -a -o 'CMD[A-Z]*[ -~]*' "${TMP}/tty.log")"
}
cmds() { printf '%s\n' "${WIRE}" | sed 's/,.*//' | tr '\n' ' '; }
VERSION="$(cat "${ROOT}/VERSION")"

if command -v xxd >/dev/null 2>&1; then
  preview "focus -"
  ok "it sets the display up as the daemon does, and shows the menu" \
     "$(cmds)" "CMDFADE CMDTFADE CMDCON CMDSETTIME CMDDIM CMDFLIP CMDSCROLL CMDMETAOFF CMDBOOTPIC CMDCLOCK CMDRSS CMDNOTE "

  preview "focus METADATA_FIELDS"
  # The daemon's order on a core change, which is the behaviour (CLAUDE.md).
  ok "a console setting gets a game, sent in the daemon's own order" \
     "$(cmds | sed 's/.*CMDSCROLL //')" "CMDHEAD CMDHTIMER CMDMETAOFF CMDCOR CMDCBOOT CMDMETA CMDDESC CMDICON "
  ok "through the daemon's own field ordering: the pinned one first" \
     "$(printf '%s\n' "${WIRE}" | grep -c '^CMDMETA,2,[0-9]*,1,0,.*A Link to the Past|System=')" "1"

  preview "focus METADATA_FIELDS" "set METADATA_FIELDS Genre System" "set METADATA_PINNED Genre"
  ok "a change of fields is a game change: new details, the picture left alone" \
     "$(cmds | sed 's/.*CMDSCROLL //')" "CMDHEAD CMDHTIMER CMDMETAOFF CMDCOR CMDCBOOT CMDMETA CMDDESC CMDICON "
  ok "and they are the new ones" "$(printf '%s\n' "${WIRE}" | grep -c 'A Link to the Past|Genre=Action-adventure|System=[A-Za-z ]*$')" "1"

  preview "focus CONTRAST" "set CONTRAST 90" "set CONTRAST 95" "set CONTRAST 100"
  ok "a run of values is shown once, where it ended" \
     "$(printf '%s\n' "${WIRE}" | grep '^CMDCON' | tr '\n' ' ')" "CMDCON,255 CMDCON,100 "

  preview "focus ARCADE_PINNED"
  ok "an arcade setting gets the card, at once" "$(cmds | sed 's/.*CMDHTIMER //')" "CMDMETAOFF CMDCOR CMDMETA CMDDESC CMDSHMETA "
  preview "focus DVD_FIELDS"
  ok "a film's gets a film, playing" "$(printf '%s\n' "${WIRE}" | tail -n1)" "CMDMEDIA,1,1325,5760,4,12"
  preview "focus UPDATE_ALL_TEXT" "set UPDATE_ALL_TEXT Fetching..."
  ok "an update screen's text is the busy screen's label" \
     "$(printf '%s\n' "${WIRE}" | grep -c '^CMDBUSY,1,Fetching\.\.\.,')" "1"
  preview "focus UPDATE_NOTE_TEXT"
  ok "the notice is shown under the menu" "$(printf '%s\n' "${WIRE}" | tail -n1)" "CMDNOTE,TTY2OLED+ Update Available"
  preview "focus TRANSITION" "set TRANSITION 5"
  ok "an effect is tried on a picture" "$(printf '%s\n' "${WIRE}" | grep -c '^CMDCOR,[A-Za-z]*,5$')" "1"
  preview "focus DIM_CONTRAST" "set DIM_CONTRAST 30" "~" "focus CONTRAST"
  ok "dimming is shown after two seconds, and the real time put back after" \
     "$(printf '%s\n' "${WIRE}" | grep '^CMDDIM' | tail -n2 | tr '\n' ' ')" "CMDDIM,2,30,-1,6000 CMDDIM,120,30,-1,6000 "
  preview "focus FLIP_MINUTES" "~" "focus CONTRAST"
  ok "and the side swap every eight" \
     "$(printf '%s\n' "${WIRE}" | grep '^CMDFLIP' | tr '\n' ' ')" "CMDFLIP,300 CMDFLIP,8 CMDFLIP,300 "
  preview "focus SAM_HEADER_TEXT" "set SAM_HEADER_TEXT Demo mode"
  ok "the header is Super Attract Mode's while its settings are in hand" \
     "$(printf '%s\n' "${WIRE}" | grep '^CMDHEAD' | tail -n1)" "CMDHEAD,Demo mode"
  preview "focus SHOW_METADATA" "~" "set SHOW_METADATA no"
  ok "game details off is the core's picture alone, the layout taken down first" \
     "$(cmds | sed 's/.*CMDICON //')" "CMDMETAOFF CMDCOR "
  preview "focus CONTRAST" "set TTYDEV /dev/null" "set PATH /nope" "set NOT_SET_ANYWHERE 1" "set CONTRAST 7"
  ok "the port and anything that is not a setting are not its to change" \
     "$(printf '%s\n' "${WIRE}" | grep '^CMDCON' | tail -n1)" "CMDCON,7"

  bash "${PI}/tty2oledplus_preview.sh" --install "${PI}" --check >/dev/null 2>&1; RC="${?}"
  ok "--check with no display there says so" "${RC}" "1"
else
  printf '  \033[33mskip\033[0m no xxd: the preview sends pictures through it\n'
fi

# Every setting offered has a scene: one named, or the default. This is here
# for the next setting added - it lands on the console game unless it is put
# somewhere, which a clock or an update message must be.
SCENES="$(sed -n '/^scene_of()/,/^}/p' "${ROOT}/tools/tty2oledplus_preview.sh")"
ok "the preview names the scenes it has" \
   "$(printf '%s\n' "${SCENES}" | grep -o 'SCENE_WANT="[a-z]*"' | sort -u | tr '\n' ' ')" \
   'SCENE_WANT="arcade" SCENE_WANT="busy" SCENE_WANT="console" SCENE_WANT="dvd" SCENE_WANT="menu" SCENE_WANT="transition" '

# ---------------------------------------------------------------------------
printf '\n\033[1mResults:\033[0m %d passed, %d failed\n' "${PASS}" "${FAIL}"
[ "${FAIL}" -eq 0 ]
