// genfont.cpp - the settings utility's fonts, taken from the display's own.
//
// The utility on the TV is meant to look like the panel, so it is set in the
// faces the firmware draws with: this renders each printable ASCII glyph of
// a u8g2 font with the real U8g2_for_Adafruit_GFX and writes the bitmaps out
// as fonts.h, which is committed - the MiSTer build needs no Arduino library.
//
//   genfont <name> <u8g2 font> ...   > fonts.h      (tools/settings-ui/genfont.sh)
//
// A glyph is FONT_ROWS_W bits a row, bit 0 being FONT_XOFF pixels left of the
// pen: u8g2 glyphs may start left of it.

#include <Arduino.h>
#include <Adafruit_GFX.h>
#include <U8g2_for_Adafruit_GFX.h>
#include <cstdio>
#include <cstring>

unsigned long millis(void) { return 0; }
void delay(unsigned long) { }

#define CW 40
#define CH 40
#define XOFF 2

class Cell : public Adafruit_GFX {
public:
  uint8_t px[CH][CW];
  Cell() : Adafruit_GFX(CW, CH) { clear(); }
  void clear() { memset(px, 0, sizeof px); }
  void drawPixel(int16_t x, int16_t y, uint16_t c) override {
    if (x >= 0 && x < CW && y >= 0 && y < CH) px[y][x] = c ? 1 : 0;
  }
};

struct Named { const char *name; const uint8_t *font; };
#define F(n) { #n, u8g2_font_##n }
static const Named known[] = {
  F(5x7_mf), F(5x8_mf), F(6x10_mf), F(6x12_mf), F(6x13_mf), F(6x13B_mf), F(7x13_mf), F(7x13B_mf),
  F(tenfatguys_tr), F(tenthinguys_tr), F(luBS08_tf), F(profont11_mf), F(profont12_mf),
  F(haxrcorp4089_tr), F(t0_11_mf), F(t0_12_mf), F(t0_12b_mf), F(t0_13_mf), F(t0_13b_mf),
};

int main(int argc, char **argv) {
  Cell cell;
  U8G2_FOR_ADAFRUIT_GFX u8;
  u8.begin(cell);
  u8.setFontMode(1);
  u8.setForegroundColor(1);

  printf("// Generated by tools/settings-ui/genfont.sh from the u8g2 fonts the firmware\n");
  printf("// draws with. Do not edit: run the script again.\n\n");
  printf("#define FONT_XOFF %d\n\n", XOFF);
  printf("typedef struct {\n  int height, ascent;\n  const unsigned char *adv;\n  const unsigned int *rows;\n} Font;\n\n");

  for (int a = 1; a + 1 < argc; a += 2) {
    const uint8_t *font = NULL;
    for (size_t i = 0; i < sizeof known / sizeof known[0]; i++)
      if (!strcmp(known[i].name, argv[a + 1])) font = known[i].font;
    if (!font) { fprintf(stderr, "genfont: no font %s\n", argv[a + 1]); return 1; }
    u8.setFont(font);

    // The rows any glyph touches, so every font is as tall as it is, no more.
    const int base = 24;
    int top = CH, bottom = -1;
    for (int c = 32; c < 127; c++) {
      cell.clear();
      u8.drawGlyph(XOFF, base, (uint16_t)c);
      for (int y = 0; y < CH; y++)
        for (int x = 0; x < CW; x++)
          if (cell.px[y][x]) { if (y < top) top = y; if (y > bottom) bottom = y; }
    }
    int height = bottom - top + 1;

    printf("// %s: u8g2_font_%s\n", argv[a], argv[a + 1]);
    printf("static const unsigned char font_%s_adv[95] = {", argv[a]);
    for (int c = 32; c < 127; c++) {
      // The pen's advance, which drawGlyph returns: getUTF8Width is the inked
      // width, and proportional glyphs set by it run into each other.
      cell.clear();
      printf("%s%d,", (c - 32) % 16 ? "" : "\n  ", u8.drawGlyph(XOFF, base, (uint16_t)c));
    }
    printf("\n};\nstatic const unsigned int font_%s_rows[95 * %d] = {\n", argv[a], height);
    for (int c = 32; c < 127; c++) {
      cell.clear();
      u8.drawGlyph(XOFF, base, (uint16_t)c);
      printf("  ");
      for (int y = top; y <= bottom; y++) {
        unsigned int bits = 0;
        for (int x = 0; x < 32; x++) if (cell.px[y][x]) bits |= 1u << x;
        printf("0x%x,", bits);
      }
      if (c == '\\') printf("  // backslash\n"); else printf("  // %c\n", c);
    }
    printf("};\nstatic const Font font_%s = { %d, %d, font_%s_adv, font_%s_rows };\n\n",
           argv[a], height, base - top, argv[a], argv[a]);
  }
  return 0;
}
